<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>
    <groupId>com.poiesis</groupId>
    <artifactId>poiesis-backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Poiesis Backend</name>
    <description>Agregador dos microsserviços do backend Poiesis.</description>
    <properties>
        <java.version>21</java.version>
    </properties>
    <modules>
        <module>login</module>
        <module>catalogo</module>
        <module>pedido</module>
        <module>producao</module>
        <module>relatorio</module>
        <module>customizacao</module>
        <module>gateway</module>
    </modules>
</project>
