server.port=8081
spring.application.name=login-service
spring.datasource.url=jdbc:h2:file:${POIESIS_AUTH_DB:./.run-local/auth};DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
application.jwt.secret=6c7def263503a39c18ebb81d68e5ce038a69c9b9449d46bce684bcf289dd8dce
application.jwt.expiration=900000
application.bootstrap-admin.email=admin@poiesis.com
application.bootstrap-admin.password=admin123

