server.port=8080
spring.application.name=api-gateway
spring.cloud.gateway.server.webmvc.routes[0].id=login-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://login-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/v1/auth/**
spring.cloud.gateway.server.webmvc.routes[1].id=catalogo-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://catalogo-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/v1/produtos/**
spring.cloud.gateway.server.webmvc.routes[2].id=pedido-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://pedido-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/v1/pedidos/**
spring.cloud.gateway.server.webmvc.routes[3].id=relatorio-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://relatorio-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/v1/relatorios/**
spring.cloud.gateway.server.webmvc.routes[4].id=producao-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://producao-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/v1/producao/**
spring.cloud.gateway.server.webmvc.routes[5].id=customizacao-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://customizacao-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/v1/customizacoes/**
spring.cloud.discovery.client.simple.instances.login-service[0].uri=http://localhost:8081
spring.cloud.discovery.client.simple.instances.catalogo-service[0].uri=http://localhost:8082
spring.cloud.discovery.client.simple.instances.pedido-service[0].uri=http://localhost:8083
spring.cloud.discovery.client.simple.instances.relatorio-service[0].uri=http://localhost:8084
spring.cloud.discovery.client.simple.instances.producao-service[0].uri=http://localhost:8085
spring.cloud.discovery.client.simple.instances.customizacao-service[0].uri=http://localhost:8086
application.jwt.secret=6c7def263503a39c18ebb81d68e5ce038a69c9b9449d46bce684bcf289dd8dce

